from setuptools import setup, find_packages

setup(
    name='epsAMS-HSISegmentation',
    packages=find_packages(),
    description='An easy-to-use implementation of the epsAMS model for unsupervised hyperspectral image segmentation. Based on the msiplib of Benjamin Berkels and his group at RWTH Aachen University.',
    version='0.1',
    url='https://github.com/jccohrs/epsAMS-HSISegmentation',
    author='Jan-Christopher Cohrs',
    author_email='cohrs@aices.rwth-aachen.de',
    install_requires=[
        'python=3.12',
        'atomap',
        'cerberus',
        'conda-build',
        'configargparse',
        'coscine',
        'gitpython',
        'humanize',
        'hyperopt',
        'hyperspy',
        'imageio',
        'ipython',
        'jax',
        'jupyterlab',
        'keyring',
        'matplotlib',
        'natsort',
        'ncempy',
        'netCDF4',
        'numba',
        'numexpr',
        'numpy=1.26.4',
        'openssl',
        'optuna',
        'pandas',
        'pip',
        'plotly',
        'pyfftw',
        'pylint',
        'pyqt',
        'python-kaleido',
        'pytorch',
        'qimage2ndarray',
        'scikit-image',
        'scikit-learn',
        'spectral',
        'sphinx<7.4',
        'sphinx-autodoc-typehints',
        'sphinxcontrib-bibtex',
        'tikzplotlib',
        'torchvision',
        'torchaudio',
        'tqdm',
        'umap-learn',
        'xarray',
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: Other/Proprietary License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Image Processing",
    ],
    )
